### ISSUE TITLE
Look for FirefoxNightly, FirefoxAurora and Firefox binaries

### ISSUE THREAD

**Issue by nicola** [mozilla/fireplay-sublime#58]
Maybe using mozrunner?

**Comment by nicola** [comment]
Nope, wrong. Profiles are all under Firefox..

**Comment by sole** [comment]
yeah this will be needed because we can't assume it's Firefox-I'm getting this error:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./fireplay.py", line 384, in run
  File "./fireplaylib/b2g_helper.py", line 37, in find_b2gs
OSError: [Errno 2] No such file or directory: '/Users/sole/Library/Application Support/Firefox/Profiles/6ubqqf1n.default2-chrome-debugger/extensions'
```

I guess it's because I have the simulator installed in **FirefoxNightly** but not in my stable Firefox.

**Comment by nicola** [comment]
This is because it assumes you have a profile which HAS an extension, while there could be profiles with no extensions. Instead of assuming, we have to check first if it is a folder. #65—
Typed with hands
