### ISSUE TITLE
Fireplay plugin is not getting loaded due to failure: No module named distutils

### ISSUE THREAD

**Issue by whimboo** [mozilla/fireplay-sublime#68]
Failure when loading the plugin in sublime:

Reloading plugin /home/henrik/.config/sublime-text-2/Packages/fireplay/fireplay.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./fireplay.py", line 16, in <module>
    from fireplaylib import firefox_helper
  File "./fireplaylib/firefox_helper.py", line 1, in <module>
    import mozrunner
  File "./fireplaylib/mozrunner/**init**.py", line 20, in <module>
    from distutils import dir_util
ImportError: No module named distutils

**Comment by nicola** [comment]
interesting.
I haven't seen this error yet.
Can you send us your sublime version.

Mozrunner is actually not used for the FF disabled version. This is an interesting problem here

**Comment by whimboo** [comment]
I'm on Ubuntu 14.04 with Sublime Text 2 installed:

> $ dpkg -l | grep sublime
> ii  sublime-text                                          2.0.2-1~webupd8~3                                   all          Sublime Text 2

Not sure if I wrongly set this up. I tried to best follow the steps as I could.

**Comment by nicola** [comment]
can you try to install distutils?
I may assume that it is already installed in mac, here I got no error like that.
But at the moment we are not using mozrunner, so I might even cut that off (cutting off a part of Firefox Desktop support, @sole?)

**Comment by whimboo** [comment]
distutils is installed:

> import distutils
> distutils.**file**
> '/usr/lib/python2.7/distutils/**init**.pyc'

**Comment by nicola** [comment]
Nope. You installed it for your python, not sublime one, (using 2.6).

Can you try to open the console in sublime and type import distutils?
—
Typed with hands

**Comment by whimboo** [comment]
You are right. Sublime seems to use its own Python installation at './lib/python26.zip'. So how would I have to install distutils inside of sublime?

**Comment by nicola** [comment]
You have to install distutils with a python6 and in the python6 path!

I think I will just try to cut this reference
—
Typed with hands

**Comment by whimboo** [comment]
Nope. That location already has distutils too. So sublime might use another path, or only supports packages inside the zip archive?
